### ISSUE TITLE
Improvements for first versioned release

### ISSUE THREAD

**Issue by jagephart** [Seafood-Globalization-Lab/exploreARTIS#12]
- [ ] add documentation to each function, ideally with example code included
  - [x] `plot_sankey()`
  - [x] `plot_bar()`
  - [x]  `add_country_name()`
  - [x]  `add_region()`
  - [x] `convert_owid_regions()` -- do we need this? Not used in Github repos
- [x] update README to show primary functions and their range of options (e.g., including new faceting)
- [ ] #15
- [ ] #16
- [ ] #17
- [x] confirm that plot_regional_sankey_method_habitat is not needed (it might be used in ms_seafood_globalization). if it is needed, we can move it back to the R folder for the first release. (control +f `jagephart/ms-seafood-globalization` repo files, found no examples -AM 2024-06-07)
- [ ] update testing script to reflect new functions and remove old functions
  - [x] `plot_sankey()`
  - [x] `plot_bar()`
  - [ ]  `add_country_name()`
  - [ ]  `add_region()`
  - [ ] `convert_owid_regions()` -- do we need this? Not used in Github repos
- [x] remove unnecessary arguments from plot_chord 
- [x] remove unnecessary arguments from plot_map
- [ ] #18
  - [ ] value / weight
- [ ] add commenting throughout functions
- [ ] #19
- [ ] #20
- [ ] add markdown option to plot titles with `ggtext::element_markdown()` [https://stackoverflow.com/questions/32555531/how-to-italicize-part-one-or-two-words-of-an-axis-title]()
- [ ] #21

**Comment by theamarks** [comment]
- [ ] in `plot_sankey()` can remove  all `rename()`in `for(i in 1:length(cols))` chunk and iterate through colname values not index

**Comment by theamarks** [comment]
> * check region file to see if other region groupings are included (line of testing code suggests so)

@jagephart I am not entirely clear what this means. Can you provide a link to the `funciton_testing.R` part you are referring to?

**Comment by theamarks** [comment]
Do we want to remove NAs in `plot_bar()`? Currently displaying at the top of the plot with `slice_max()` default argument `na_rm = FALSE`, so already displaying filtered results.

`    # Top N bars in the bar chart
    top_n_value <- data %>%
      select(bar_group, total) %>%
      distinct() %>%
      slice_max(order_by = total, n = top_n) %>%
      pull(total) %>%
      min()`

**Comment by theamarks** [comment]
`plot_map()` warning: "The legacy packages maptools, rgdal, and rgeos, underpinning this package will retire shortly." 

Update dependencies.

**Comment by theamarks** [comment]
Batch of updates added to package for ARTIS exchange tag and release. Converted unfinished updates to new issues
